# Generated by Django 5.0.6 on 2024-07-05 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
                ('phone', models.IntegerField()),
                ('telegram_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imges', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekanom', models.CharField(max_length=255)),
                ('komfort', models.CharField(max_length=255)),
                ('lyuks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('Aviakompaniya', models.CharField(max_length=255)),
                ('Duration', models.IntegerField()),
                ('food', models.BooleanField()),
                ('visa', models.CharField(max_length=255)),
                ('help', models.IntegerField()),
                ('Jilet', models.CharField(max_length=255)),
                ('Tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarif')),
            ],
        ),
    ]
